#!/bin/bash
set -e

if [[ ! -n $(which swig) ]]; then
    echo "swig must be installed";
    exit 1
fi

BASE=$(pwd)
CORE_PATH="$BASE/../airbitz-core"
BUILD_PATH=${BUILD_DIR:-$CORE_PATH/deps/build}
WALLET_PATH="$BASE/AirBitz/airbitz/src/main"

if [[ $# -eq 1 ]]; then
    BUILD_DIR=$1
fi

# Copy the core build output into the jni folder:
mkdir -p $WALLET_PATH/jni/
mkdir -p $WALLET_PATH/jni/armeabi
mkdir -p $WALLET_PATH/jni/x86
cp $CORE_PATH/src/ABC.h $WALLET_PATH/jni/
sed  -e 's/const char *\*/const char *const /' $WALLET_PATH/jni/ABC.h \
    > $WALLET_PATH/jni/ABC-const.h
cp $BUILD_PATH/abc/android-arm/libabc.so $WALLET_PATH/jni/armeabi/libabc.so
cp $BUILD_PATH/abc/android-x86/libabc.so $WALLET_PATH/jni/x86/libabc.so

# Generate the wrapper code:
cd $WALLET_PATH
swig -java -package com.airbitz.api \
    -outdir java/com/airbitz/api -o jni/ABC_wrap.c jni/ABC.i

# Build the wrapper library:
cd $WALLET_PATH/jni/
$BUILD_PATH/ndk/android-ndk-r10d/ndk-build

# Gradle is looking in the wrong place for libraries:
cp -r $WALLET_PATH/libs/ $WALLET_PATH/jniLibs/
