#!/usr/local/bin/node

const languages = ['de', 'es', 'fr', 'hi', 'ht', 'it', 'ja', 'pt', 'ru', 'zh']
const brands = ['athena', 'rackwallet', 'coinsource']

var sys = require('sys')
var exec = require('child_process').exec;
function puts(error, stdout, stderr) { sys.puts(stdout) }

for (let l of languages) {
  for (let b of brands) {
    var src = 'Airbitz/airbitz/src/' + b + '/res/values'
    var dst = 'Airbitz/airbitz/src/' + b + '/res/values-' + l
    var cmd = 'rm -rf ' + dst
    exec (cmd)
    cmd = 'cp -a ' + src + ' ' + dst
    exec(cmd)
  }
}

