#!/bin/bash
set -e

BASE=$(pwd)
CORE_PATH="../airbitz-core/deps"
WALLET_PATH="$BASE/AirBitz/airbitz"
WALLET_MAIN="$WALLET_PATH/src/main"

cd $CORE_PATH
touch recipes/abc

if [[ ! -n $(which ndk-build) ]]; then
    echo "ndk-build must be installed";
    exit 1
fi

if [[ ! -n $(which swig) ]]; then
    echo "swig must be installed";
    exit 1
fi

echo $1
BUILD_DIR=build
if [[ "$1" == "testnet" ]]; then
    BUILD_DIR=build-testnet
    make BUILD_DIR=$BUILD_DIR ENABLE_TESTNET=1 \
        abc.build-android-arm
else
    make abc.build-android-arm
fi

mkdir -p $WALLET_MAIN/jni/
mkdir -p $WALLET_MAIN/jniLibs/armeabi/

echo $(pwd)
cp ../src/ABC.h $WALLET_MAIN/jni/
cp $BUILD_DIR/abc/android-arm/libabc.so $WALLET_MAIN/jniLibs/armeabi/

cd $WALLET_PATH
swig -java -package com.airbitz.api \
        -outdir src/main/java/com/airbitz/api \
        -o src/main/jni/ABC_wrap.c src/main/jni/ABC.i
cd src/main/jni/
$BASE/$CORE_PATH/$BUILD_DIR/ndk/android-ndk-r10d/ndk-build

cp ../libs/armeabi/libairbitz.so ../jniLibs/armeabi/

