#!/bin/bash

BASE=$(pwd)
CORE_PATH="../airbitz-core/deps"
WALLET_PATH="$BASE/AirBitz/airbitz"
WALLET_MAIN="$WALLET_PATH/src/main"

cd $CORE_PATH

if [[ ! -n $(which ndk-build) ]]; then
    echo "ndk-build must be installed";
    exit 1
fi

if [[ ! -n $(which swig) ]]; then
    echo "swig must be installed";
    exit 1
fi

echo $1
BUILD_DIR=build
if [[ "$1" == "testnet" ]]; then
    BUILD_DIR=build-testnet
    make BUILD_DIR=$BUILD_DIR ENABLE_TESTNET=1 \
        abc.clean abc.build-android-arm  abc.build-android-x86;
else
    make abc.clean abc.build-android-arm  abc.build-android-x86
fi

mkdir -p $WALLET_MAIN/jni/
mkdir -p $WALLET_MAIN/jniLibs/armeabi/
mkdir -p $WALLET_MAIN/jniLibs/x86/

echo $(pwd)
cp ../src/ABC.h $WALLET_MAIN/jni/
cp $BUILD_DIR/abc/android-arm/libabc.so $WALLET_MAIN/jniLibs/armeabi/
cp $BUILD_DIR/abc/android-x86/libabc.so $WALLET_MAIN/jniLibs/x86/

cd $WALLET_PATH
swig -java -package com.airbitz.api \
        -outdir src/main/java/com/airbitz/api \
        -o src/main/jni/ABC_wrap.c src/main/jni/ABC.i
cd src/main/jni/
ndk-build

cp ../libs/armeabi/libairbitz.so ../jniLibs/armeabi/
cp ../libs/x86/libairbitz.so ../jniLibs/x86/

