#!/bin/bash

set -u
set -e

CURRENT_DIR=$( /bin/pwd )

cd ../airbitz-plugins
find plugins -maxdepth 1 -mindepth 1 | sed -e 's/plugins\///' | xargs -I {} bash -c 'gulp {}-android;'
cd ${CURRENT_DIR}
find ../airbitz-plugins/plugins -maxdepth 1 -mindepth 1 | sed -e 's/\.\.\/airbitz-plugins\/plugins\///' | xargs -I {} bash -c 'cp ../airbitz-plugins/build/android/{}/index.html Airbitz/airbitz/src/main/assets/{}.html;'

