/**
 * Copyright (c) 2014, Airbitz Inc
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms are permitted provided that 
 * the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Redistribution or use of modified source code requires the express written
 *    permission of Airbitz Inc.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies, 
 * either expressed or implied, of the Airbitz Project.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public interface coreConstants {
  public final static int ABC_MAX_STRING_LENGTH = coreJNI.ABC_MAX_STRING_LENGTH_get();
  public final static int ABC_BITCOIN_DECIMAL_PLACES = coreJNI.ABC_BITCOIN_DECIMAL_PLACES_get();
  public final static int ABC_EXCHANGE_RATE_REFRESH_INTERVAL_SECONDS = coreJNI.ABC_EXCHANGE_RATE_REFRESH_INTERVAL_SECONDS_get();
  public final static int ABC_DENOMINATION_BTC = coreJNI.ABC_DENOMINATION_BTC_get();
  public final static int ABC_DENOMINATION_MBTC = coreJNI.ABC_DENOMINATION_MBTC_get();
  public final static int ABC_DENOMINATION_UBTC = coreJNI.ABC_DENOMINATION_UBTC_get();
  public final static String ABC_VERSION = coreJNI.ABC_VERSION_get();
  public final static int ABC_MIN_USERNAME_LENGTH = coreJNI.ABC_MIN_USERNAME_LENGTH_get();
  public final static int ABC_MIN_PASS_LENGTH = coreJNI.ABC_MIN_PASS_LENGTH_get();
  public final static int ABC_MIN_PIN_LENGTH = coreJNI.ABC_MIN_PIN_LENGTH_get();
  public final static int ABC_GET_TX_ALL_TIMES = coreJNI.ABC_GET_TX_ALL_TIMES_get();
}
