/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_ExchangeRateSources {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_ExchangeRateSources(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_ExchangeRateSources obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_ExchangeRateSources(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumSources(long value) {
    coreJNI.tABC_ExchangeRateSources_numSources_set(swigCPtr, this, value);
  }

  public long getNumSources() {
    return coreJNI.tABC_ExchangeRateSources_numSources_get(swigCPtr, this);
  }

  public void setASources(SWIGTYPE_p_p_sABC_ExchangeRateSource value) {
    coreJNI.tABC_ExchangeRateSources_aSources_set(swigCPtr, this, SWIGTYPE_p_p_sABC_ExchangeRateSource.getCPtr(value));
  }

  public SWIGTYPE_p_p_sABC_ExchangeRateSource getASources() {
    long cPtr = coreJNI.tABC_ExchangeRateSources_aSources_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_sABC_ExchangeRateSource(cPtr, false);
  }

  public tABC_ExchangeRateSources() {
    this(coreJNI.new_tABC_ExchangeRateSources(), true);
  }

}
