/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_TxInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_TxInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_TxInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_TxInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzID(String value) {
    coreJNI.tABC_TxInfo_szID_set(swigCPtr, this, value);
  }

  public String getSzID() {
    return coreJNI.tABC_TxInfo_szID_get(swigCPtr, this);
  }

  public void setSzMalleableTxId(String value) {
    coreJNI.tABC_TxInfo_szMalleableTxId_set(swigCPtr, this, value);
  }

  public String getSzMalleableTxId() {
    return coreJNI.tABC_TxInfo_szMalleableTxId_get(swigCPtr, this);
  }

  public void setTimeCreation(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_TxInfo_timeCreation_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getTimeCreation() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_TxInfo_timeCreation_get(swigCPtr, this), true);
  }

  public void setCountOutputs(long value) {
    coreJNI.tABC_TxInfo_countOutputs_set(swigCPtr, this, value);
  }

  public long getCountOutputs() {
    return coreJNI.tABC_TxInfo_countOutputs_get(swigCPtr, this);
  }

  public void setAOutputs(SWIGTYPE_p_p_sABC_TxOutput value) {
    coreJNI.tABC_TxInfo_aOutputs_set(swigCPtr, this, SWIGTYPE_p_p_sABC_TxOutput.getCPtr(value));
  }

  public SWIGTYPE_p_p_sABC_TxOutput getAOutputs() {
    long cPtr = coreJNI.tABC_TxInfo_aOutputs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_sABC_TxOutput(cPtr, false);
  }

  public void setPDetails(tABC_TxDetails value) {
    coreJNI.tABC_TxInfo_pDetails_set(swigCPtr, this, tABC_TxDetails.getCPtr(value), value);
  }

  public tABC_TxDetails getPDetails() {
    long cPtr = coreJNI.tABC_TxInfo_pDetails_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tABC_TxDetails(cPtr, false);
  }

  public tABC_TxInfo() {
    this(coreJNI.new_tABC_TxInfo(), true);
  }

}
