/**
 * Copyright (c) 2014, Airbitz Inc
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms are permitted provided that 
 * the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Redistribution or use of modified source code requires the express written
 *    permission of Airbitz Inc.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies, 
 * either expressed or implied, of the Airbitz Project.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_WalletInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_WalletInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_WalletInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_WalletInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzUUID(String value) {
    coreJNI.tABC_WalletInfo_szUUID_set(swigCPtr, this, value);
  }

  public String getSzUUID() {
    return coreJNI.tABC_WalletInfo_szUUID_get(swigCPtr, this);
  }

  public void setSzName(String value) {
    coreJNI.tABC_WalletInfo_szName_set(swigCPtr, this, value);
  }

  public String getSzName() {
    return coreJNI.tABC_WalletInfo_szName_get(swigCPtr, this);
  }

  public void setSzUserName(String value) {
    coreJNI.tABC_WalletInfo_szUserName_set(swigCPtr, this, value);
  }

  public String getSzUserName() {
    return coreJNI.tABC_WalletInfo_szUserName_get(swigCPtr, this);
  }

  public void setCurrencyNum(int value) {
    coreJNI.tABC_WalletInfo_currencyNum_set(swigCPtr, this, value);
  }

  public int getCurrencyNum() {
    return coreJNI.tABC_WalletInfo_currencyNum_get(swigCPtr, this);
  }

  public void setArchived(long value) {
    coreJNI.tABC_WalletInfo_archived_set(swigCPtr, this, value);
  }

  public long getArchived() {
    return coreJNI.tABC_WalletInfo_archived_get(swigCPtr, this);
  }

  public void setBalanceSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_WalletInfo_balanceSatoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getBalanceSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_WalletInfo_balanceSatoshi_get(swigCPtr, this), true);
  }

  public tABC_WalletInfo() {
    this(coreJNI.new_tABC_WalletInfo(), true);
  }

}
