/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_WalletInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_WalletInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_WalletInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_WalletInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzUUID(String value) {
    coreJNI.tABC_WalletInfo_szUUID_set(swigCPtr, this, value);
  }

  public String getSzUUID() {
    return coreJNI.tABC_WalletInfo_szUUID_get(swigCPtr, this);
  }

  public void setSzName(String value) {
    coreJNI.tABC_WalletInfo_szName_set(swigCPtr, this, value);
  }

  public String getSzName() {
    return coreJNI.tABC_WalletInfo_szName_get(swigCPtr, this);
  }

  public void setCurrencyNum(int value) {
    coreJNI.tABC_WalletInfo_currencyNum_set(swigCPtr, this, value);
  }

  public int getCurrencyNum() {
    return coreJNI.tABC_WalletInfo_currencyNum_get(swigCPtr, this);
  }

  public void setArchived(long value) {
    coreJNI.tABC_WalletInfo_archived_set(swigCPtr, this, value);
  }

  public long getArchived() {
    return coreJNI.tABC_WalletInfo_archived_get(swigCPtr, this);
  }

  public void setBalanceSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_WalletInfo_balanceSatoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getBalanceSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_WalletInfo_balanceSatoshi_get(swigCPtr, this), true);
  }

  public tABC_WalletInfo() {
    this(coreJNI.new_tABC_WalletInfo(), true);
  }

}
