/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_QuestionChoice {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_QuestionChoice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_QuestionChoice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_QuestionChoice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzQuestion(String value) {
    coreJNI.tABC_QuestionChoice_szQuestion_set(swigCPtr, this, value);
  }

  public String getSzQuestion() {
    return coreJNI.tABC_QuestionChoice_szQuestion_get(swigCPtr, this);
  }

  public void setSzCategory(String value) {
    coreJNI.tABC_QuestionChoice_szCategory_set(swigCPtr, this, value);
  }

  public String getSzCategory() {
    return coreJNI.tABC_QuestionChoice_szCategory_get(swigCPtr, this);
  }

  public void setMinAnswerLength(long value) {
    coreJNI.tABC_QuestionChoice_minAnswerLength_set(swigCPtr, this, value);
  }

  public long getMinAnswerLength() {
    return coreJNI.tABC_QuestionChoice_minAnswerLength_get(swigCPtr, this);
  }

  public tABC_QuestionChoice() {
    this(coreJNI.new_tABC_QuestionChoice(), true);
  }

}
