/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_RequestInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_RequestInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_RequestInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_RequestInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzID(String value) {
    coreJNI.tABC_RequestInfo_szID_set(swigCPtr, this, value);
  }

  public String getSzID() {
    return coreJNI.tABC_RequestInfo_szID_get(swigCPtr, this);
  }

  public void setTimeCreation(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_RequestInfo_timeCreation_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getTimeCreation() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_RequestInfo_timeCreation_get(swigCPtr, this), true);
  }

  public void setPDetails(tABC_TxDetails value) {
    coreJNI.tABC_RequestInfo_pDetails_set(swigCPtr, this, tABC_TxDetails.getCPtr(value), value);
  }

  public tABC_TxDetails getPDetails() {
    long cPtr = coreJNI.tABC_RequestInfo_pDetails_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tABC_TxDetails(cPtr, false);
  }

  public void setAmountSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_RequestInfo_amountSatoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getAmountSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_RequestInfo_amountSatoshi_get(swigCPtr, this), true);
  }

  public void setOwedSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_RequestInfo_owedSatoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getOwedSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_RequestInfo_owedSatoshi_get(swigCPtr, this), true);
  }

  public tABC_RequestInfo() {
    this(coreJNI.new_tABC_RequestInfo(), true);
  }

}
