/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_ExchangeRateSource {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_ExchangeRateSource(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_ExchangeRateSource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_ExchangeRateSource(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurrencyNum(int value) {
    coreJNI.tABC_ExchangeRateSource_currencyNum_set(swigCPtr, this, value);
  }

  public int getCurrencyNum() {
    return coreJNI.tABC_ExchangeRateSource_currencyNum_get(swigCPtr, this);
  }

  public void setSzSource(String value) {
    coreJNI.tABC_ExchangeRateSource_szSource_set(swigCPtr, this, value);
  }

  public String getSzSource() {
    return coreJNI.tABC_ExchangeRateSource_szSource_get(swigCPtr, this);
  }

  public tABC_ExchangeRateSource() {
    this(coreJNI.new_tABC_ExchangeRateSource(), true);
  }

}
