/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_PasswordRule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_PasswordRule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_PasswordRule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_PasswordRule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzDescription(String value) {
    coreJNI.tABC_PasswordRule_szDescription_set(swigCPtr, this, value);
  }

  public String getSzDescription() {
    return coreJNI.tABC_PasswordRule_szDescription_get(swigCPtr, this);
  }

  public void setBPassed(boolean value) {
    coreJNI.tABC_PasswordRule_bPassed_set(swigCPtr, this, value);
  }

  public boolean getBPassed() {
    return coreJNI.tABC_PasswordRule_bPassed_get(swigCPtr, this);
  }

  public tABC_PasswordRule() {
    this(coreJNI.new_tABC_PasswordRule(), true);
  }

}
