/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_TransferDetails {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_TransferDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_TransferDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_TransferDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzSrcWalletUUID(String value) {
    coreJNI.tABC_TransferDetails_szSrcWalletUUID_set(swigCPtr, this, value);
  }

  public String getSzSrcWalletUUID() {
    return coreJNI.tABC_TransferDetails_szSrcWalletUUID_get(swigCPtr, this);
  }

  public void setSzSrcName(String value) {
    coreJNI.tABC_TransferDetails_szSrcName_set(swigCPtr, this, value);
  }

  public String getSzSrcName() {
    return coreJNI.tABC_TransferDetails_szSrcName_get(swigCPtr, this);
  }

  public void setSzSrcCategory(String value) {
    coreJNI.tABC_TransferDetails_szSrcCategory_set(swigCPtr, this, value);
  }

  public String getSzSrcCategory() {
    return coreJNI.tABC_TransferDetails_szSrcCategory_get(swigCPtr, this);
  }

  public void setSzDestWalletUUID(String value) {
    coreJNI.tABC_TransferDetails_szDestWalletUUID_set(swigCPtr, this, value);
  }

  public String getSzDestWalletUUID() {
    return coreJNI.tABC_TransferDetails_szDestWalletUUID_get(swigCPtr, this);
  }

  public void setSzDestName(String value) {
    coreJNI.tABC_TransferDetails_szDestName_set(swigCPtr, this, value);
  }

  public String getSzDestName() {
    return coreJNI.tABC_TransferDetails_szDestName_get(swigCPtr, this);
  }

  public void setSzDestCategory(String value) {
    coreJNI.tABC_TransferDetails_szDestCategory_set(swigCPtr, this, value);
  }

  public String getSzDestCategory() {
    return coreJNI.tABC_TransferDetails_szDestCategory_get(swigCPtr, this);
  }

  public tABC_TransferDetails() {
    this(coreJNI.new_tABC_TransferDetails(), true);
  }

}
