/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_TxDetails {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_TxDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_TxDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_TxDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAmountSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_TxDetails_amountSatoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getAmountSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_TxDetails_amountSatoshi_get(swigCPtr, this), true);
  }

  public void setAmountFeesAirbitzSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_TxDetails_amountFeesAirbitzSatoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getAmountFeesAirbitzSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_TxDetails_amountFeesAirbitzSatoshi_get(swigCPtr, this), true);
  }

  public void setAmountFeesMinersSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_TxDetails_amountFeesMinersSatoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getAmountFeesMinersSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_TxDetails_amountFeesMinersSatoshi_get(swigCPtr, this), true);
  }

  public void setSzLogin(String value) {
    coreJNI.tABC_TxDetails_szLogin_set(swigCPtr, this, value);
  }

  public String getSzLogin() {
    return coreJNI.tABC_TxDetails_szLogin_get(swigCPtr, this);
  }

  public void setAmountCurrency(double value) {
    coreJNI.tABC_TxDetails_amountCurrency_set(swigCPtr, this, value);
  }

  public double getAmountCurrency() {
    return coreJNI.tABC_TxDetails_amountCurrency_get(swigCPtr, this);
  }

  public void setSzName(String value) {
    coreJNI.tABC_TxDetails_szName_set(swigCPtr, this, value);
  }

  public String getSzName() {
    return coreJNI.tABC_TxDetails_szName_get(swigCPtr, this);
  }

  public void setBizId(long value) {
    coreJNI.tABC_TxDetails_bizId_set(swigCPtr, this, value);
  }

  public long getBizId() {
    return coreJNI.tABC_TxDetails_bizId_get(swigCPtr, this);
  }

  public void setSzCategory(String value) {
    coreJNI.tABC_TxDetails_szCategory_set(swigCPtr, this, value);
  }

  public String getSzCategory() {
    return coreJNI.tABC_TxDetails_szCategory_get(swigCPtr, this);
  }

  public void setSzNotes(String value) {
    coreJNI.tABC_TxDetails_szNotes_set(swigCPtr, this, value);
  }

  public String getSzNotes() {
    return coreJNI.tABC_TxDetails_szNotes_get(swigCPtr, this);
  }

  public void setAttributes(long value) {
    coreJNI.tABC_TxDetails_attributes_set(swigCPtr, this, value);
  }

  public long getAttributes() {
    return coreJNI.tABC_TxDetails_attributes_get(swigCPtr, this);
  }

  public tABC_TxDetails() {
    this(coreJNI.new_tABC_TxDetails(), true);
  }

}
