/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_RequestResults {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_RequestResults(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_RequestResults obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_RequestResults(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRequestType(tABC_RequestType value) {
    coreJNI.tABC_RequestResults_requestType_set(swigCPtr, this, value.swigValue());
  }

  public tABC_RequestType getRequestType() {
    return tABC_RequestType.swigToEnum(coreJNI.tABC_RequestResults_requestType_get(swigCPtr, this));
  }

  public void setPData(SWIGTYPE_p_void value) {
    coreJNI.tABC_RequestResults_pData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPData() {
    long cPtr = coreJNI.tABC_RequestResults_pData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPRetData(SWIGTYPE_p_void value) {
    coreJNI.tABC_RequestResults_pRetData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPRetData() {
    long cPtr = coreJNI.tABC_RequestResults_pRetData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setBSuccess(boolean value) {
    coreJNI.tABC_RequestResults_bSuccess_set(swigCPtr, this, value);
  }

  public boolean getBSuccess() {
    return coreJNI.tABC_RequestResults_bSuccess_get(swigCPtr, this);
  }

  public void setSzWalletUUID(String value) {
    coreJNI.tABC_RequestResults_szWalletUUID_set(swigCPtr, this, value);
  }

  public String getSzWalletUUID() {
    return coreJNI.tABC_RequestResults_szWalletUUID_get(swigCPtr, this);
  }

  public void setErrorInfo(tABC_Error value) {
    coreJNI.tABC_RequestResults_errorInfo_set(swigCPtr, this, tABC_Error.getCPtr(value), value);
  }

  public tABC_Error getErrorInfo() {
    long cPtr = coreJNI.tABC_RequestResults_errorInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tABC_Error(cPtr, false);
  }

  public tABC_RequestResults() {
    this(coreJNI.new_tABC_RequestResults(), true);
  }

}
