/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_airbitz_api_AirbitzAPI */

#ifndef _Included_com_airbitz_api_AirbitzAPI
#define _Included_com_airbitz_api_AirbitzAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABCInitialize
 * Signature: (Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/BitcoinEventCallback;Lcom/airbitz/api/AirbitzAPI;[CILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABCInitialize
  (JNIEnv *, jobject, jstring, jobject, jobject, jcharArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_ClearKeyCache
 * Signature: (Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1ClearKeyCache
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_SignIn
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/RequestCallback;Lcom/airbitz/api/AirbitzAPI;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1SignIn
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_CreateAccount
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/RequestCallback;Lcom/airbitz/api/AirbitzAPI;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1CreateAccount
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_SetAccountRecoveryQuestions
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/RequestCallback;Lcom/airbitz/api/AirbitzAPI;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1SetAccountRecoveryQuestions
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_CreateWallet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILcom/airbitz/api/AirbitzAPI/RequestCallback;Lcom/airbitz/api/AirbitzAPI;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1CreateWallet
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jobject, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetCurrencies
 * Signature: ([Lcom/airbitz/api/AirbitzAPI/ABC_Currency;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetCurrencies
  (JNIEnv *, jobject, jobjectArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetPIN
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetPIN
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_SetPIN
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1SetPIN
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetCategories
 * Signature: (Ljava/lang/String;[[Ljava/lang/String;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetCategories
  (JNIEnv *, jobject, jstring, jobjectArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_AddCategory
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1AddCategory
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_RemoveCategory
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1RemoveCategory
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_RenameWallet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1RenameWallet
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_SetWalletAttributes
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1SetWalletAttributes
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_CheckRecoveryAnswers
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1CheckRecoveryAnswers
  (JNIEnv *, jobject, jstring, jstring, jboolean, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetWalletInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Lcom/airbitz/api/AirbitzAPI/ABC_WalletInfo;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetWalletInfo
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeWalletInfo
 * Signature: (Lcom/airbitz/api/AirbitzAPI/ABC_WalletInfo;)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeWalletInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetWallets
 * Signature: (Ljava/lang/String;Ljava/lang/String;[[Lcom/airbitz/api/AirbitzAPI/ABC_WalletInfo;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetWallets
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeWalletInfoArray
 * Signature: ([Lcom/airbitz/api/AirbitzAPI/ABC_WalletInfo;I)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeWalletInfoArray
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_SetWalletOrder
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1SetWalletOrder
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetQuestionChoices
 * Signature: (Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/RequestCallback;Lcom/airbitz/api/AirbitzAPI;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetQuestionChoices
  (JNIEnv *, jobject, jstring, jobject, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeQuestionChoices
 * Signature: (Lcom/airbitz/api/AirbitzAPI/ABC_QuestionChoices;)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeQuestionChoices
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetRecoveryQuestions
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetRecoveryQuestions
  (JNIEnv *, jobject, jstring, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_ChangePassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/RequestCallback;Lcom/airbitz/api/AirbitzAPI;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1ChangePassword
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_ChangePasswordWithRecoveryAnswers
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/RequestCallback;Lcom/airbitz/api/AirbitzAPI;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1ChangePasswordWithRecoveryAnswers
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_ParseBitcoinURI
 * Signature: (Ljava/lang/String;[Lcom/airbitz/api/AirbitzAPI/ABC_BitcoinURIInfo;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1ParseBitcoinURI
  (JNIEnv *, jobject, jstring, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeURIInfo
 * Signature: (Lcom/airbitz/api/AirbitzAPI/ABC_BitcoinURIInfo;)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeURIInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_SatoshiToBitcoin
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1SatoshiToBitcoin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_BitcoinToSatoshi
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1BitcoinToSatoshi
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_SatoshiToCurrency
 * Signature: (JDILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1SatoshiToCurrency
  (JNIEnv *, jobject, jlong, jdouble, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_CurrencyToSatoshi
 * Signature: (DIJLcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1CurrencyToSatoshi
  (JNIEnv *, jobject, jdouble, jint, jlong, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_CreateReceiveRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_TxDetails;[Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1CreateReceiveRequest
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_ModifyReceiveRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_TxDetails;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1ModifyReceiveRequest
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FinalizeReceiveRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FinalizeReceiveRequest
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_CancelReceiveRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1CancelReceiveRequest
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GenerateRequestQRCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GenerateRequestQRCode
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_InitiateSendRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_TxDetails;Lcom/airbitz/api/AirbitzAPI/RequestCallback;Lcom/airbitz/api/AirbitzAPI;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1InitiateSendRequest
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject, jobject, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Lcom/airbitz/api/AirbitzAPI/ABC_TxInfo;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetTransaction
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetTransactions
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[[Lcom/airbitz/api/AirbitzAPI/ABC_TxInfo;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetTransactions
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeTransaction
 * Signature: (Lcom/airbitz/api/AirbitzAPI/ABC_TxInfo;)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeTransaction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeTransactions
 * Signature: ([Lcom/airbitz/api/AirbitzAPI/ABC_TxInfo;I)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeTransactions
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_SetTransactionDetails
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_TxDetails;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1SetTransactionDetails
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetTransactionDetails
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Lcom/airbitz/api/AirbitzAPI/ABC_TxDetails;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetTransactionDetails
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetRequestAddress
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetRequestAddress
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_GetPendingRequests
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[[Lcom/airbitz/api/AirbitzAPI/ABC_RequestInfo;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1GetPendingRequests
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeRequests
 * Signature: ([Lcom/airbitz/api/AirbitzAPI/ABC_RequestInfo;I)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeRequests
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_DuplicateTxDetails
 * Signature: ([Lcom/airbitz/api/AirbitzAPI/ABC_TxDetails;Lcom/airbitz/api/AirbitzAPI/ABC_TxDetails;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1DuplicateTxDetails
  (JNIEnv *, jobject, jobjectArray, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeTxDetails
 * Signature: (Lcom/airbitz/api/AirbitzAPI/ABC_TxDetails;)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeTxDetails
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_CheckPassword
 * Signature: (Ljava/lang/String;D[[Lcom/airbitz/api/AirbitzAPI/ABC_PasswordRule;ILcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1CheckPassword
  (JNIEnv *, jobject, jstring, jdouble, jobjectArray, jint, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreePasswordRuleArray
 * Signature: ([Lcom/airbitz/api/AirbitzAPI/ABC_PasswordRule;I)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreePasswordRuleArray
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_LoadAccountSettings
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Lcom/airbitz/api/AirbitzAPI/ABC_AccountSettings;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1LoadAccountSettings
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_UpdateAccountSettings
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/airbitz/api/AirbitzAPI/ABC_AccountSettings;Lcom/airbitz/api/AirbitzAPI/ABC_Error;)I
 */
JNIEXPORT jint JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1UpdateAccountSettings
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject);

/*
 * Class:     com_airbitz_api_AirbitzAPI
 * Method:    ABC_FreeAccountSettings
 * Signature: (Lcom/airbitz/api/AirbitzAPI/ABC_AccountSettings;)V
 */
JNIEXPORT void JNICALL Java_com_airbitz_api_AirbitzAPI_ABC_1FreeAccountSettings
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_RequestCallback */

#ifndef _Included_com_airbitz_api_AirbitzAPI_RequestCallback
#define _Included_com_airbitz_api_AirbitzAPI_RequestCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_BitcoinEventCallback */

#ifndef _Included_com_airbitz_api_AirbitzAPI_BitcoinEventCallback
#define _Included_com_airbitz_api_AirbitzAPI_BitcoinEventCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_AccountSettings */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_AccountSettings
#define _Included_com_airbitz_api_AirbitzAPI_ABC_AccountSettings
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_BitcoinDenomination */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_BitcoinDenomination
#define _Included_com_airbitz_api_AirbitzAPI_ABC_BitcoinDenomination
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_ExchangeRateSources */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_ExchangeRateSources
#define _Included_com_airbitz_api_AirbitzAPI_ABC_ExchangeRateSources
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_ExchangeRateSource */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_ExchangeRateSource
#define _Included_com_airbitz_api_AirbitzAPI_ABC_ExchangeRateSource
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_PasswordRule */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_PasswordRule
#define _Included_com_airbitz_api_AirbitzAPI_ABC_PasswordRule
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_RequestInfo */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_RequestInfo
#define _Included_com_airbitz_api_AirbitzAPI_ABC_RequestInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_TxInfo */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_TxInfo
#define _Included_com_airbitz_api_AirbitzAPI_ABC_TxInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_TxDetails */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_TxDetails
#define _Included_com_airbitz_api_AirbitzAPI_ABC_TxDetails
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_BitcoinURIInfo */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_BitcoinURIInfo
#define _Included_com_airbitz_api_AirbitzAPI_ABC_BitcoinURIInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_QuestionChoices */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_QuestionChoices
#define _Included_com_airbitz_api_AirbitzAPI_ABC_QuestionChoices
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_QuestionChoice */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_QuestionChoice
#define _Included_com_airbitz_api_AirbitzAPI_ABC_QuestionChoice
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_WalletInfo */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_WalletInfo
#define _Included_com_airbitz_api_AirbitzAPI_ABC_WalletInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_Currency */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_Currency
#define _Included_com_airbitz_api_AirbitzAPI_ABC_Currency
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_airbitz_api_AirbitzAPI_ABC_Error */

#ifndef _Included_com_airbitz_api_AirbitzAPI_ABC_Error
#define _Included_com_airbitz_api_AirbitzAPI_ABC_Error
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
