/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public interface coreConstants {
  public final static int ABC_MAX_STRING_LENGTH = coreJNI.ABC_MAX_STRING_LENGTH_get();
  public final static int ABC_BITCOIN_DECIMAL_PLACES = coreJNI.ABC_BITCOIN_DECIMAL_PLACES_get();
  public final static int ABC_EXCHANGE_RATE_REFRESH_INTERVAL_SECONDS = coreJNI.ABC_EXCHANGE_RATE_REFRESH_INTERVAL_SECONDS_get();
  public final static int NETWORK_FAKE = coreJNI.NETWORK_FAKE_get();
}
