/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_BitcoinURIInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_BitcoinURIInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_BitcoinURIInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_BitcoinURIInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzLabel(String value) {
    coreJNI.tABC_BitcoinURIInfo_szLabel_set(swigCPtr, this, value);
  }

  public String getSzLabel() {
    return coreJNI.tABC_BitcoinURIInfo_szLabel_get(swigCPtr, this);
  }

  public void setSzAddress(String value) {
    coreJNI.tABC_BitcoinURIInfo_szAddress_set(swigCPtr, this, value);
  }

  public String getSzAddress() {
    return coreJNI.tABC_BitcoinURIInfo_szAddress_get(swigCPtr, this);
  }

  public void setSzMessage(String value) {
    coreJNI.tABC_BitcoinURIInfo_szMessage_set(swigCPtr, this, value);
  }

  public String getSzMessage() {
    return coreJNI.tABC_BitcoinURIInfo_szMessage_get(swigCPtr, this);
  }

  public void setAmountSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_BitcoinURIInfo_amountSatoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getAmountSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_BitcoinURIInfo_amountSatoshi_get(swigCPtr, this), true);
  }

  public tABC_BitcoinURIInfo() {
    this(coreJNI.new_tABC_BitcoinURIInfo(), true);
  }

}
