/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.airbitz.api;

public class tABC_BitcoinDenomination {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tABC_BitcoinDenomination(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tABC_BitcoinDenomination obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        coreJNI.delete_tABC_BitcoinDenomination(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSzLabel(String value) {
    coreJNI.tABC_BitcoinDenomination_szLabel_set(swigCPtr, this, value);
  }

  public String getSzLabel() {
    return coreJNI.tABC_BitcoinDenomination_szLabel_get(swigCPtr, this);
  }

  public void setSatoshi(SWIGTYPE_p_int64_t value) {
    coreJNI.tABC_BitcoinDenomination_satoshi_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getSatoshi() {
    return new SWIGTYPE_p_int64_t(coreJNI.tABC_BitcoinDenomination_satoshi_get(swigCPtr, this), true);
  }

  public tABC_BitcoinDenomination() {
    this(coreJNI.new_tABC_BitcoinDenomination(), true);
  }

}
