#!/bin/bash

CORE_PATH="../../../airbitz-walletcore/deps"
WALLET_PATH="../../airbitz-wallet-ui-android/AirBitz/airbitz"
WALLET_MAIN="$WALLET_PATH/src/main"
LIB_PATH="build/abc/android-arm/libabc.so"

cd $CORE_PATH

if [[ ! -n $(which ndk-build) ]]; then
    echo "ndk-build must be installed";
    exit 1
fi

if [[ ! -n $(which swig) ]]; then
    echo "swig must be installed";
    exit 1
fi

make abc.build-android-arm 

mkdir -p $WALLET_MAIN/jniLibs/armeabi/
mkdir -p $WALLET_MAIN/jni/

cp ../src/ABC.h $WALLET_MAIN/jni/
cp $LIB_PATH $WALLET_MAIN/jni/
cp $LIB_PATH $WALLET_MAIN/jniLibs/armeabi/

cd $WALLET_PATH
swig -java -package com.airbitz.api \
        -outdir src/main/java/com/airbitz/api \
        -o src/main/jni/ABC_wrap.c src/main/jni/ABC.i
cd src/main/jni/
ndk-build 
cp ../libs/armeabi/libairbitz.so ../jniLibs/armeabi/ 
